### POST to send a chat
POST  http://localhost:3000/api/v1/chat
Content-Type: application/json

 {
   "message": "What is MERN stack. Is Node in this stack too?",
   "fileIds": ["69832814bcbfb72ff41315e6"]
 }
